version: '3.5'

services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile-dev
    env_file:
      - app/.env
    ports:
      - "50000:50000"
    volumes:
      - ./app:/app
    restart: always
    networks:
      - learn_serbian_frontend_network

networks:
  learn_serbian_frontend_network:
